server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: shop-advice

  main:
    banner-mode: off

  profiles:
    active: ${ACTIVE_PROFILES}

  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=60m

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:flyway/migrations
    validate-migration-naming: true

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true
    path: /api-docs

